# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Dealership.create(name: "Ereve", city: "Lith Harbor")
Dealership.create(name: "Rien", city: "Ellinia")
Dealership.create(name: "Grandis", city: "Henesys")
Dealership.create(name: "Victoria", city: "Kerning City")
Dealership.create(name: "Maple", city: "Tree Hill")
Dealership.create(name: "Ossyria", city: "Southperry")

Vehicle.create(make: "BMW", model: "M3", year: 2016, dealership_vehicle_id: 1)
Vehicle.create(make: "Toyota", model: "Corolla", year: 2016, dealership_vehicle_id: 2)
Vehicle.create(make: "Ford", model: "Escape", year: 2016, dealership_vehicle_id: 1)
Vehicle.create(make: "Chevrolet", model: "Malibu", year: 2016, dealership_vehicle_id: 3)
Vehicle.create(make: "Volkswage", model: "Beetle", year: 2016, dealership_vehicle_id: 4)
Vehicle.create(make: "Volkswage", model: "Caddy", year: 2010, dealership_vehicle_id: 5)
Vehicle.create(make: "Volkswage", model: "Passat", year: 2010, dealership_vehicle_id: 6)
Vehicle.create(make: "Volkswage", model: "Tiguan", year: 2010, dealership_vehicle_id: 1)
Vehicle.create(make: "BMW", model: "3 Series", year: 2010, dealership_vehicle_id: 2)
Vehicle.create(make: "BMW", model: "i8", year: 2010, dealership_vehicle_id: 3)
Vehicle.create(make: "BMW", model: "M6", year: 2015, dealership_vehicle_id: 4)
Vehicle.create(make: "BMW", model: "X3", year: 2015, dealership_vehicle_id: 5)
Vehicle.create(make: "Volvo", model: "S60", year: 2015, dealership_vehicle_id: 6)
Vehicle.create(make: "Volvo", model: "S80", year: 2015, dealership_vehicle_id: 1)
Vehicle.create(make: "Volvo", model: "V40", year: 2015, dealership_vehicle_id: 2)
Vehicle.create(make: "Volvo", model: "XC60", year: 2011, dealership_vehicle_id: 3)
Vehicle.create(make: "Nissan", model: "Altima", year: 2011, dealership_vehicle_id: 4)
Vehicle.create(make: "Nissan", model: "GT-R", year: 2011, dealership_vehicle_id: 5)
Vehicle.create(make: "Nissan", model: "Patrol", year: 2011, dealership_vehicle_id: 6)
Vehicle.create(make: "Nissan", model: "Micra", year: 2011, dealership_vehicle_id: 1)
Vehicle.create(make: "Nissan", model: "Navara", year: 2014, dealership_vehicle_id: 2)
Vehicle.create(make: "Honda", model: "Accord", year: 2014, dealership_vehicle_id: 3)
Vehicle.create(make: "Honda", model: "Civic", year: 2014, dealership_vehicle_id: 4)
Vehicle.create(make: "Honda", model: "Ridgeline", year: 2014, dealership_vehicle_id: 5)
Vehicle.create(make: "Honda", model: "Oddyssey", year: 2014, dealership_vehicle_id: 6)
Vehicle.create(make: "Kia", model: "Stinger", year: 2017, dealership_vehicle_id: 1)
Vehicle.create(make: "Kia", model: "Soul", year: 2017, dealership_vehicle_id: 2)

Employee.create(name: "Bill Gates", manager: true, email: "bill.gates@gmail.com", password: "password", dealership_id: 1)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates1@gmail.com", password: "password", dealership_id: 2)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates2@gmail.com", password: "password", dealership_id: 3)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates3@gmail.com", password: "password", dealership_id: 4)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates4@gmail.com", password: "password", dealership_id: 5)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates5@gmail.com", password: "password", dealership_id: 6)
Employee.create(name: "Grace Hopper", manager: true, email: "grace.hopper@gmail.com", password: "password", dealership_id: 2)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates6@gmail.com", password: "password", dealership_id: 1)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates7@gmail.com", password: "password", dealership_id: 3)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates8@gmail.com", password: "password", dealership_id: 4)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates9@gmail.com", password: "password", dealership_id: 5)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates11@gmail.com", password: "password", dealership_id: 6)
Employee.create(name: "Linus Torvalds", manager: true, email: "linus.torvalds@gmail.com", password: "password", dealership_id: 3)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates22@gmail.com", password: "password", dealership_id: 2)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates33@gmail.com", password: "password", dealership_id: 1)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates44@gmail.com", password: "password", dealership_id: 4)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates55@gmail.com", password: "password", dealership_id: 5)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates66@gmail.com", password: "password", dealership_id: 6)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates77@gmail.com", password: "password", dealership_id: 1)
Employee.create(name: "Bill Gates", manager: false, email: "bill.gates88@gmail.com", password: "password", dealership_id: 2)

DealershipVehicle.create(dealership_id: 1, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 2, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 4, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 5, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 6, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 1, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 2, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 4, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 5, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 6, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 1, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 2, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 4, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 5, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 6, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 1, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 2, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)
DealershipVehicle.create(dealership_id: 3, buyer: "Tom", price: 20000)